# setup
setup: scan

# Loss
criterion: scan
criterion_kwargs:
   entropy_weight: 5.0

# Weight update
update_cluster_head_only: False # Update full network in SCAN
num_heads: 1 # Only use one head

# Model
backbone: resnet50  #!!CHANGED FROM Resnet50!!

# Dataset
train_db_name: batsnet
val_db_name: batsnet
num_classes: 5
num_neighbors: 20

# Transformations
augmentation_strategy: batsnet_strategy 
augmentation_kwargs:
   crop_size: 360
   normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 16
     random: True

transformation_kwargs:
   crop_size: 360
   normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
epochs: 30
batch_size: 5
num_workers: 8

# Scheduler
scheduler: constant
